[workspace]
channels = ["conda-forge", "avcopan"]
platforms = ["linux-64", "osx-64", "osx-arm64"]
preview = ["pixi-build"]

[dependencies]
higher-level-package = { path = "." }
lower-level-package = ">=0.0.0,<0.0.1"

[package]
name = "higher-level-package"
version = "0.0.0"

[package.build]
backend = { name = "pixi-build-python", version = "*" }

[package.build.config]
ignore-pyproject-manifest = false
ignore-pypi-mapping = false

[feature.dev.pypi-dependencies]
# local dependencies placeholder

[feature.dev.pypi-options.dependency-overrides]
# local dependencies placeholder

[environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default"}
